random:
  seed: 42
dataset:
  filepath: "arxiv-metadata-oai-snapshot.json"
  max_size: 100000
  train_size: 80000
  val_size: 20000
  categories: ['stat.ML','cs.CV','cs.AI', 'cs.CL', 'cs.LG', 'cs.NE']
encoder:
  tokenizer_path: "facebook/bart-large"
datamodule:
  batch_size: 2
model:
  model_name: "facebook/bart-large"
optimizer:
  name: "Adam"
  args:
    lr: 3e-5
trainer:
  gpus: 1
  progress_bar_refresh_rate: 25
  max_epochs: 5
  deterministic: True
  val_check_interval: 0.25
  num_sanity_val_steps: 0
  accumulate_grad_batches: 4
checkpoint_path: "./checkpoints/{epoch}"
